app = "superrely-fly"
primary_region = "bom"

[build]
  dockerfile = "Dockerfile"

[mounts]
  source = "gun_data"
  destination = "/app/data"

# THIS IS THE NEW FIX
[deploy]
  strategy = "immediate"

[[services]]
  internal_port = 8765
  protocol = "tcp"
  # Set this to true to let Fly manage the machines
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
