app = "superrely-fly"
primary_region = "bom"

[build]
  dockerfile = "Dockerfile"

# This connects the volume you created (Crucial!)
[mounts]
  source = "gun_data"
  destination = "/app/data"

[[services]]
  # CHANGE THIS: Match your code's port
  internal_port = 8765
  protocol = "tcp"
  
  # Prevent the app from sleeping (Gun needs to stay awake)
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
