name: Create Volume
on: workflow_dispatch
jobs:
  create-vol:
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      - run: flyctl apps create superrely-fly --org personal || echo "App might already exist"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      # Added --yes here to skip the confirmation prompt
      - run: flyctl volumes create gun_data --size 1 --region bom --app superrely-fly --yes
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
