name: Create Volume
on: workflow_dispatch
jobs:
  create-vol:
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      # Ensure app exists first
      - run: flyctl apps create superrely-fly --org personal || echo "App might already exist"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      # Create volume for 'superrely-fly'
      - run: flyctl volumes create gun_data --size 1 --region bom --app superrely-fly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
